spring.application.name=visitor-task-service
server.port=9090
spring.security.user.name=user
spring.security.user.password=password123
spring.datasource.url=jdbc:h2:mem:poc_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=dbuser
spring.datasource.password=dbuser123
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret.key=MTIzNDU2NzgxMjM0NTY3ODEyMzQ1Njc4MTIzNDU2Nzg=
jwt.secret.expiration_time=600000
pagination.default.page.size=10

# Set root logging level
logging.level.root=INFO
# Set specific package or class logging level
#logging.level.com.example.task=DEBUG
# Customize log output pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
# Change log file name
logging.file.name=vts-app.log
# Change log file path
logging.file.path=logs

